spring:
  datasource:
    url: jdbc:mysql://serwer1809686.home.pl:3306/28504352_webapp
    username: 28504352_webapp
    password: P@55word
    maximumPoolSize: 2
    
 
    
management:
  endpoints:
    web:
      expose:"*"    